[project]
name = 'LotDap'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.main]
path = 'contracts/main.clar'
clarity_version = 2
epoch = 2.5

[contracts.prize]
path = 'contracts/prize.clar'
clarity_version = 2
epoch = 2.5

[contracts.ticket]
path = 'contracts/ticket.clar'
clarity_version = 2
epoch = 2.5

[contracts.winner]
path = 'contracts/winner.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
